# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/vsmart/casuarina/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter casuarina,$(TARGET_DEVICE)),)

endif
